### ISSUE TITLE
npm-install.sh fails when aws command is available

### ISSUE THREAD

**Issue by haavard** [balena-io/scripts#7]
When running `npm-install.sh` (via `make develop`), if the `aws` command is available, but AWS keys are not, then the script errors out because it tries to access the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` with the `nounset` option enabled.

     /build/etcher/src/etcher/scripts/resin/electron/../shared/npm-install.sh: line 240: AWS_ACCESS_KEY_ID: unbound variable

**Comment by imrehg** [comment]
@haavard `make develop -i` will fix that for you, as it's not a bug, but default behaviour. With `-i` the cache is not tried to be uploaded, see

https://github.com/balena-io/scripts/blob/8baa9e9a4063edc0b597baf16e266e28ed460b94/shared/npm-install.sh#L44

Cc @thundron as we've discussed before.

**Comment by haavard** [comment]
The `-i` in that command is consumed by `make`, and is not passed to `npm-install.sh`. Relevant excerpt from the `make(1)` manpage:

    -i, --ignore-errors
         Ignore all errors in commands executed to remake files.

The `-i` flag just makes it ignore all errors, including the one in the issue. This is obviously not a desired outcome, as we would very much like errors to be errors.
